import http from 'node:http';
import { GoogleAuth } from 'google-auth-library';
import { evaluateVerdict, validateRequestBinding } from './verdict.js';

const port = Number(process.env.PORT ?? 8080);
const expectedPackageName = process.env.EXPECTED_PACKAGE_NAME ?? 'com.resistine.android';
const expectedCertificateSha256 = process.env.EXPECTED_CERTIFICATE_SHA256 || undefined;
const auth = new GoogleAuth({ scopes: ['https://www.googleapis.com/auth/playintegrity'] });
const usedActions = new Map();
const rateBuckets = new Map();

function sendJson(response, status, value) {
  const body = JSON.stringify(value);
  response.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'no-store',
    'content-length': Buffer.byteLength(body)
  });
  response.end(body);
}

async function readJson(request) {
  let raw = '';
  for await (const chunk of request) {
    raw += chunk;
    if (Buffer.byteLength(raw) > 64 * 1024) throw new Error('Request body is too large.');
  }
  return JSON.parse(raw);
}

function pruneUsedActions(now = Date.now()) {
  for (const [actionId, expiresAt] of usedActions) {
    if (expiresAt <= now) usedActions.delete(actionId);
  }
}

function allowRequest(address, now = Date.now()) {
  const key = address || 'unknown';
  const bucket = rateBuckets.get(key);
  if (!bucket || now - bucket.windowStartedAt >= 60_000) {
    rateBuckets.set(key, { windowStartedAt: now, count: 1 });
    return true;
  }
  if (bucket.count >= 30) return false;
  bucket.count += 1;
  return true;
}

async function decodeToken(token) {
  const client = await auth.getClient();
  const url = `https://playintegrity.googleapis.com/v1/${encodeURIComponent(expectedPackageName)}:decodeIntegrityToken`;
  const response = await client.request({
    url,
    method: 'POST',
    data: { integrity_token: token }
  });
  return response.data?.tokenPayloadExternal;
}

async function handleVerify(request, response) {
  const body = await readJson(request);
  if (typeof body.token !== 'string' || body.token.length < 20) {
    return sendJson(response, 400, { valid: false, message: 'Missing integrity token.' });
  }

  const payload = await decodeToken(body.token);
  if (!payload) throw new Error('Google Play did not return a decoded token payload.');
  const binding = validateRequestBinding({ body, payload, expectedPackageName });
  pruneUsedActions();
  if (usedActions.has(binding.actionId)) {
    return sendJson(response, 409, { valid: false, message: 'This integrity action was already used.' });
  }
  usedActions.set(binding.actionId, Date.now() + 2 * 60 * 1000);

  return sendJson(response, 200, evaluateVerdict(payload, {
    expectedPackageName,
    expectedCertificateSha256
  }));
}

const server = http.createServer(async (request, response) => {
  response.setHeader('x-content-type-options', 'nosniff');
  if (request.method === 'GET' && request.url === '/healthz') {
    return sendJson(response, 200, { ok: true });
  }
  if (request.method !== 'POST' || request.url !== '/v1/integrity/verify') {
    return sendJson(response, 404, { message: 'Not found.' });
  }
  if (!allowRequest(request.socket.remoteAddress)) {
    return sendJson(response, 429, { valid: false, message: 'Too many integrity requests.' });
  }
  try {
    await handleVerify(request, response);
  } catch (error) {
    const knownValidationMessages = [
      'Unexpected package name.',
      'Invalid action identifier.',
      'Invalid action timestamp.',
      'Action request is stale.',
      'Integrity token is stale.',
      'Request hash was not generated by this action.',
      'Decoded token request hash mismatch.',
      'Decoded token package mismatch.',
      'Request body is too large.'
    ];
    const rawMessage = String(error?.message || '');
    const message = error instanceof SyntaxError
      ? 'Malformed JSON request.'
      : (knownValidationMessages.includes(rawMessage)
          ? rawMessage
          : 'Integrity verification failed.');
    const status = error instanceof SyntaxError || knownValidationMessages.includes(rawMessage)
      ? 400
      : 502;
    sendJson(response, status, { valid: false, message: String(message).slice(0, 240) });
  }
});

server.listen(port, '0.0.0.0', () => {
  process.stdout.write(`Resistine integrity verifier listening on port ${port}\n`);
});
