import { createHash, timingSafeEqual } from 'node:crypto';

export const MAX_TOKEN_AGE_MILLIS = 2 * 60 * 1000;

export function canonicalAction(packageName, actionId, timestampMillis) {
  return `${packageName}|${actionId}|${timestampMillis}|environment_check`;
}

export function requestHash(packageName, actionId, timestampMillis) {
  return createHash('sha256')
    .update(canonicalAction(packageName, actionId, timestampMillis), 'utf8')
    .digest('base64url');
}

function equalText(left, right) {
  const leftBytes = Buffer.from(String(left));
  const rightBytes = Buffer.from(String(right));
  return leftBytes.length === rightBytes.length && timingSafeEqual(leftBytes, rightBytes);
}

function stringArray(value) {
  return Array.isArray(value) ? value.filter((item) => typeof item === 'string') : [];
}

export function validateRequestBinding({ body, payload, expectedPackageName, now = Date.now() }) {
  const request = payload?.requestDetails ?? {};
  const packageName = String(body?.packageName ?? '');
  const actionId = String(body?.actionId ?? '');
  const timestampMillis = Number(body?.timestampMillis);
  const suppliedHash = String(body?.requestHash ?? '');
  const tokenTimestamp = Number(request.timestampMillis);

  if (!packageName || packageName !== expectedPackageName) throw new Error('Unexpected package name.');
  if (!actionId || actionId.length > 128) throw new Error('Invalid action identifier.');
  if (!Number.isSafeInteger(timestampMillis)) throw new Error('Invalid action timestamp.');
  if (Math.abs(now - timestampMillis) > MAX_TOKEN_AGE_MILLIS) throw new Error('Action request is stale.');
  if (!Number.isSafeInteger(tokenTimestamp) || Math.abs(now - tokenTimestamp) > MAX_TOKEN_AGE_MILLIS) {
    throw new Error('Integrity token is stale.');
  }

  const expectedHash = requestHash(packageName, actionId, timestampMillis);
  if (!equalText(suppliedHash, expectedHash)) throw new Error('Request hash was not generated by this action.');
  if (!equalText(request.requestHash ?? '', expectedHash)) throw new Error('Decoded token request hash mismatch.');
  if (!equalText(request.requestPackageName ?? '', expectedPackageName)) {
    throw new Error('Decoded token package mismatch.');
  }

  return { actionId, expectedHash };
}

export function evaluateVerdict(payload, { expectedPackageName, expectedCertificateSha256 } = {}) {
  const app = payload?.appIntegrity ?? {};
  const device = stringArray(payload?.deviceIntegrity?.deviceRecognitionVerdict);
  const environment = payload?.environmentDetails ?? {};
  const appAccessRisk = stringArray(environment?.appAccessRiskVerdict?.appsDetected);
  const playProtectVerdict = environment?.playProtectVerdict ?? 'UNEVALUATED';
  const licensingVerdict = payload?.accountDetails?.appLicensingVerdict ?? 'UNEVALUATED';
  const appIntegrity = app?.appRecognitionVerdict ?? 'UNEVALUATED';
  const certificates = stringArray(app?.certificateSha256Digest);

  const appPackageMatches = !expectedPackageName || app.packageName === expectedPackageName;
  const certificateMatches = !expectedCertificateSha256 || certificates.includes(expectedCertificateSha256);
  const deviceMeetsIntegrity = device.includes('MEETS_DEVICE_INTEGRITY') ||
    device.includes('MEETS_STRONG_INTEGRITY');
  const accessRisks = appAccessRisk.filter((item) =>
    item.includes('CAPTURING') || item.includes('CONTROLLING') || item.includes('OVERLAYS'));
  const unknownAccessRisk = accessRisks.some((item) => item.startsWith('UNKNOWN_'));

  const concerns = [];
  if (appIntegrity !== 'PLAY_RECOGNIZED') concerns.push('app recognition');
  if (!appPackageMatches) concerns.push('app package');
  if (!certificateMatches) concerns.push('app certificate');
  if (!deviceMeetsIntegrity) concerns.push('device integrity');
  if (playProtectVerdict !== 'NO_ISSUES') concerns.push('Play Protect');
  if (licensingVerdict !== 'LICENSED') concerns.push('Play licensing');
  if (accessRisks.length) concerns.push('app access risk');

  let remediationDialogType;
  if (unknownAccessRisk) remediationDialogType = 2;
  else if (accessRisks.length) remediationDialogType = 3;
  else if (playProtectVerdict !== 'NO_ISSUES') remediationDialogType = 5;
  else if (appIntegrity !== 'PLAY_RECOGNIZED' || !appPackageMatches ||
    !certificateMatches || !deviceMeetsIntegrity) remediationDialogType = 4;
  else if (licensingVerdict !== 'LICENSED') remediationDialogType = 1;

  return {
    valid: true,
    decision: concerns.length === 0 ? 'TRUSTED' : 'REVIEW',
    message: concerns.length === 0
      ? 'Google Play verified the app and device environment.'
      : `Review required for: ${concerns.join(', ')}.`,
    appIntegrity,
    deviceIntegrity: device,
    playProtectVerdict,
    appAccessRisk,
    licensingVerdict,
    ...(remediationDialogType ? { remediationDialogType } : {})
  };
}
